### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ahmadawais**
## ZSH Aliases

For ZSH users I created a few awesome aliases just put them in your .zshrc file.

``` bash
# how2 StackExchange search
alias how="how2 $*"
alias howwp="how2 -l wordpress $*"
alias howphp="how2 -l php $*"

# Usage: how lang then question
# E.g. howl php create array in OOP
# $1 is agrument 1
# ${@:2} is everything from argument 2 to end
alias howl="how2 -l $1 ${@:2}"

```

### CODE REVIEW

**Comment by danielkop** [comment]
Great idea. But perhaps we should have a separate Aliases.md file with alias recommendations, organized by shell type?

**Comment by ahmadawais** [comment]
You can merge this and create the separate files. I use ZSH, so that's what I use. Thanks for the cool script.

**Comment by danyshaanan** [comment]
@ahmadawais This could look nicer in the history if squashed to a single commit.

**Comment by ahmadawais** [comment]
True! So, should I submit a new one?

**Comment by danielkop** [comment]
It's probably safe to squash the commits in this case
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

But you can also create a new branch from master and apply the changes in a single commit.

**Comment by danyshaanan** [comment]
I'm for squashing and force-pushing, (just in this case of a temp fork's branch). This will automatically update the pull request.

**Pull request closed without merging**
