### PR TITLE
Add a new syntax: how to <question>

### PR DESCRIPTION
**Pull request by huytd**
Add a new syntax:

```
how to <question>
```

So, from now we have a truth magic in our terminal, for example:

```
how to deploy golang app
```

```
how to create a pull request
```

Why? Because... why not? :laughing:

### CODE REVIEW

**Comment by santinic** [comment]
Oh, nice. I don't know if people expect to have an extra "how" binary when they install how2

**Comment by huytd** [comment]
Yeah, I just noticed that after create a pull request. I added a new commit to remove an extra binary https://github.com/huytd/how2/commit/fd7cc0410747a74b9881c5fe7aa6f4a8787757e6

**Comment by huytd** [comment]
I don't think there is a binary named `how` existed already in any OS :D so this should be ok?

**Comment by zdravkoggeorgiev** [comment]
IMHO only *how* is too general word

**Comment by zunc** [comment]
that's nice idea :+1:

**Comment by danielkop** [comment]
Perhaps the solution should be:
Ignore a "to" prefex in the question. treat "how2 to install npm" as "how2 install npm"
This would allow users to set up an alias "how" = "how2", while sticking to the original binary name.

**Comment by danyshaanan** [comment]
:+1: for @danielkop's solution that will not take up another bin, which is a greedy practice.

**Comment by huytd** [comment]
Well... it's should be a good.

How about this: We still based on @danielkop's solution but instead of ignoring `to` prefix for all the call, we will check for the `first` parameter. Only ignore them if it is `how` (user aliased). If the `first` parameter still matched `how2`, we just keep it as it is? :D

**Comment by danielkop** [comment]
// Add support for 'how to' command
if (argv['$0'] === 'how') {
    argv._.splice(0, 1);
}

Removes the second word regardless of whether it's "to" or not.
So "how npm install" only searches for "install".
probably better to make sure argv['$1'].toLowerCase === 'to' before splicing it.

**Pull request closed without merging**
